label chapter_1:

    scene bg school at bg_fit
    with dissolve

    yujin "(I don't remember walking to school.)"
    yujin "(But everything looks normal.)"
    yujin "(Everyone is here, except.. why does it feel like I've done this before?)"
    yujin "Whats' the date?"
    classmate "September fourteenth."
    yujin "September fourteenth."
    yujin "(My stomach dropped. I knew that date, and I really didn't believe it was happening again.)"
    yujin "What time is it?"
    classmate "Eight thirty-two."
    yujin "(That's when I met Jeha yesterday.)"
    yujin "(I looked around for him, but his seat was empty.)"
    yujin "Has Jeha come to school yet?"
    classmate "Jeha? Yeah, I saw him earlier, he said he was looking for you."
    yujin "(I stopped breathing for a second. Yesterday, Jeha never came looking for me.)"
    yujin "(I suddenly remembered the boy in the hallway, tha black faces, and the way he talked to me like we'd already met hundreds of times.)"
    yujin "(Did I wake up in the same day.. or maybe I never left it?)"
    jeha "You look like you've seen a ghost."
    yujin "(I nearly jumped out of my seat.)"
    yujin "Jeha.."
    jeha "Yeah? What's wrong?"
    yujin "Nothing.. I just.. had a weird dream."
    jeha "About me?"
    yujin "(Normally, I couldn't laugh at that.. but this time I couldn't.)"
    yujin "I don't know."
    yujin "(I wanted to tell him everything.. but something stopped me.)"
    yujin "(The boy's voice came back to me.)"
    extra "You came back."
    yujin "(I looked toward the classroom door.)"
    yujin "(He was standing there.)"
    extra "You're still trying to save him."
    yujin "(Nobody else reacted.. no one even looked at him.)"
    yujin "Who are you?"
    extra "You actually don't remember me?"
    yujin "(I didn't answer.)"
    extra "That's okay.. you will."
    yujin "(The bell rang, and he disappeared.)"
    yujin "(I spent the rest of the morning pretending nothing happened.)"
    yujin "(But when lunch started, I noticed something written on the corner of my notebook.)"
    yujin "(Four hundred.)"

    jump chapter_2