label chapter_4:
    scene bg school at bg_fit
    with dissolve

    yujin "(I stopped trying to save Jeha.)"
    yujin "(I stopped trying to predict what would happen next.)"
    yujin "(Instead, I followed the extra.)"
    yujin "So where are we going?"
    extra "Somewhere you haven't been."
    yujin "I've been here before."
    extra "No."
    extra "You haven't."
    yujin "(We reached the end of the hallway.)"
    yujin "(Ther was a door between the science lab and the stairs.)"
    yujin "(I had walked past this hallway hundreds of times.)"
    yujin "(There had never been a door there.)"
    extra "Open it."
    yujin "What's inside?"
    yujin "(I opened the door.)"
    extra "You."
    scene bg classroom at bg_fit
    with dissolve
    yujin "(It was a classroom.)"
    yujin "(Every desk was facing the wall.)"
    yujin "(Every chair was occupied.)"
    yujin "(But there wasn't anyone sitting in them.)"
    yujin "(Just names.)"
    yujin "(Hundreds of names had been written across the backs of the chairs.)"
    yujin "(Some were scratched out, and some had been written over so many times that I couldn't read them.)"
    yujin "(I recognized Jeha's.)"
    yujin "(I recognized mine.)"
    yujin "(Then I saw today's date written on the blackboard.)"
    yujin "September fourteenth."
    exta "Yes."
    yujin "Why is it written here?"
    extra "Because it always starts here."
    yujin "(I turned around.)"
    yujin "(The door was gone.)"
    yujin "Where's the door?"
    etra "It isn't supposed to be here."
    yujin "What do you mean?"
    extra "You're asking the wrong question."
    yujin "What am I supposed to ask?"
    extra "Who is missing?"
    yujin "(I looked at the chairs again.)"
    yujin "(There were names everywhere.)"
    yujin "(Jeha.)"
    yujin "(Me.)"
    yujin "(Students I remembered, and some I didn't.)"
    yujin "(And one empty chair.)"
    yujin "Whose chair is that?"
    extra "Mine."
    yujin "But your name isn't on it?"
    extra "It was."
    yujin "What happened to it?"
    extra "You read it."
    yujin "When?"
    extra "Before you came here."
    yujin "(I stared at him but for some reason I couldn't see his face.)"
    yujin "What's your name?"
    extra "Tell me."
    extra "You already did."
    yujin "(Something moved behind me.)"
    yjin "(One of the empty chairs had turned around.)"

    jump chapter_5