label chapter_4:
    scene bg school at bg_fit
    with dissolve

    yujin "(I stopped trying to save Jeha.)"
    yujin "(For the first time since I entered the world, I ignored the story completely.)"
    yujin "(I followed the extra instead.)"
    yujin "What's your name?"
    extra "You used to know it."
    yujin "I don't."
    extra "That's the problem."
    yujin "(He took me to an empty classroom at the end of the school.)"
    yujin "(Thare were hundreds of names written across the walls.)"
    yujin "(Most of them had been crossed out.)"
    yujin "(Some were names I recognized from the book.)"
    yujin "(Others weren't.)"
    yujin "Whtat is this?"
    extra "The people you forgot."
    yujin "(I looked closer.)"
    yujin "(My name was there.)"
    yujin "(So was Jeha's.)"
    yujin "(And underneath was another name.)"
    yujin "That's you."
    extra "It used to be."
    yujin "(I felt something inside my head crack open.)"
    yujin "(Memories started coming back.)"
    yujin "(I remembered seeing him before I ever entered the book.)"
    yujin "(I remembered talking to him.)"
    yujin "(And then I remembered what happened.)"
    yujin "(The story erased him, the world reset.)"
    yujin "You were supposed to be the male lead."
    extra "I was supposed to be nothing."
    yujin "(I looked at him, and suddenly everything made sense.)"
    extra "You kept choosing Jeha because that's what the story wanted."
    extra "And every time you did, it killed me first."
    yujin "I'm sorry."
    extra "Don't apologize."
    extra "Just choose differently this time."

    jump chapter_5