label chapter_5:
    scene bg classroom at bg_fit
    with fade

    yujin "(The chair was facing me.)"
    yujin "(There was a name carved into the back.)"
    yujin "(I couldn't read it.)"
    yujin "(Every time I tried, the letters seemed to change.)"
    yujin "What does it say?"
    menu:
        "Try to read the name.":
            yujin "(I forced myself to look at the letters.)"
            yujin "(They wouldn't stay still.)"
            $ remembered_extra = turned
        "Look away.":
            yujin "(I looked away.)"
            yujin "(Something about that name made me uncomfortable.)"
    extra "You tell me."
    yujin "I can't."
    extra "You could before."
    yujin "(I ooked at him.)"
    yujin "(His face was still impossible to see.)"
    yujin "(I looked at him.)"
    yujin "(His face was impossible to see.)"
    yujin "Why can't I see you?"
    menu:
        "Ask him to show his face.":
            yujin "Show me."
            extra "You really want to see?"
            yujin "Yes."
            $ trusted_extra = True
        "Don't answer.":
            yujin "(I didn't ask again.)"
    extra "Because you don't remember me."
    yujin "Then help me remember."
    etra "I can't."
    yujin "Why?"
    etra "Because I don't know what you'll remember."
    yujin "(I didn't understand.)"
    yujin "(Then I heard something behind me.)"
    yujin "(A chair against the floor.)"
    yujin "(Then came another.)"
    yujin "(Then another.)"
    yujin "(Then another.)"
    yujin "(I slowly turned around.)"
    yujin "(The chairs were moving.)"
    yujin "(One by one, they were turning away from the wall.)"
    yujin "(Every empty chair was now facing me.)"
    yujin "(I recognized some of the names.)"
    yujin "(Students from my class.)"
    yujin "(Students who disappeared during the outbreak.)"
    yujin "(Students who were never supposed to disappear.)"
    yujin "(Then I saw Jeha's chair.)"
    yujin "(It was empty.)"
    yujin "Where's Jeha?"
    extra "Where you left him."
    yujin "I didn't leave him."
    extra "You always do."
    yujin "(I stared at him.)"
    yujin "What does that mean?"
    extra "Every time you find me, you stop looking for him."
    yujin "I've only found you once."
    extra "That's what you remember."
    yujin "(The room suddenly becomes quiet.)"
    yujin "(I looked at the blackboard.)"
    yujin "(There was something written on it that hadn't been there before.)"
    yujin "(YOU HAVE 03:17 LEFT.)"
    yujin "Left for what?"
    extra "I don't know."
    yujin "You're lying."
    extra "I wish I was."
    yujin "(The clock above the blackboard started ticking.)"
    yujin "(03:16.)"
    yujin "(03:15.)"
    yujin "(03:14.)"
    yujin "(The extra suddenly grabbed my wrist.)"
    extra "Listen to me."
    yujin "What?"
    extra "When the bell rings, don't open your eyes."
    yujin "Why?"
    extra "Because you'll see him."
    yujin "Why?"
    extra "Because you'll see him."
    yujin "Jeha?"
    extra "No."
    yujin "(The clock stopped.)"
    yujin "(03:00.)"
    yujin "(Every chair turned toward the door.)"
    yujin "(I heard the footsteps outside.)"
    yujin "(Slowly approaching.)"
    yujin "(The extra let go of my wrist.)"
    yujin "What is that?"
    extra "The beginning."
    extra "The beginning of what?"
    extra "The part you keep forgetting."
    yujin "(The footsteps stopped outside the classroom.)"
    yujin "(Someone knocked.)"
    yujin "(Three times.)"
    yujin "(I knew that knock.)"
    yujin "(I had heard it before.)"
    yujin "(Hundreds of times.)"
    yujin "(I just couldn't remember where.)"

    jump chapter_6