label ending_jeha:
    yujin "(I walked toward Jeha.)"
    jeha "There you are."
    yujin "(He smiled.)"
    yujin "(For a moment, I forgot everything.)"
    jeha "I wanted to tell you something."
    yujin "(I already knew what he was going to say.)"
    jeha "I love you."
    yujin "I love you too."
    yujin "(The hallway became completely silent.)"
    yujin "(Everyone disappeared.)"
    yujin "(Jeha disappeared.)"
    yujin "(The school disappeared.)"
    yujin "(Everything became white.)"
    yujin "You chose him again."
    yujin "(I opened my eyes.)"
    yujin "(I was sitting at my desk.)"
    yujin "(September fourteenth.)"
    yujin "(Eight thirty-two.)"
    yujin "(Everything was exactly where it belonged.)"
    yujin "(Except the seat beside me.)"
    yujin "(Someone had scratched a name into it.)"
    yujin "(Mine.)"

    return

label ending_extra:
    yujin "(I turned around.)"
    yujin "(Jeh called my name.)"
    yujin "(I didn't answer.)"
    yujin "(I walked in the opposite direction.)"
    yujin "(The hallway becamse longer.)"
    yujin "(The classroom disappeared one by one.)"
    yujin "(Until there was nothing left except the door.)"
    yujin "(The same door.)"
    yujin "(I opened it.)"

    scene bg classroom at bg_fit
    with dissolve

    yujin "(The extra was sitting in the empty chair.)"
    yujin "(For the first time, I could see his face.)"
    yujin "(And I remembered his name.)"
    yujin "I remember you."
    extra "I know."
    yujin "What's your name?"
    extra "You already know."
    yujin "(I smiled.)"
    yujin "(Then I realised something.)"
    yujin "(I couldn't remember Jeha's face anymore.)"
    yujin "(I couldn't remember his voice.)"
    yujin "(The classrom door closed.)"
    yujin "(This time, from the inside.)"
    
    return

label ending_unknown:
    yujin "(I didn't move.)"
    jeha "Yujin?"
    yujin "(I looked at him.)"
    yujin "(Then I looked down the empty hallway.)"
    yujin "(I knew what the story wanted.)"
    yujin "(I knew what the extra wanted.)"
    yujin "(And for the first time, I realised that nobody has ever asked me what I wanted.)"
    yujin "I'n not going."
    jeha "What?"
    yujin "I'm not going anywhere."
    yujin "(The hallway flickered.)"
    yujin "(Jeha's face changed for a second.)"
    yujin "(Into something I couldn't recognize.)"
    yujin "(Then everything went black.)"
    yujin "(I heard the classroom door open.)"
    yujin "(I heard hundreds of chairs scraping against the floor.)"
    yujin "(Then the extra spoke.)"
    extra "You finally did it."
    yujin "Did what?"
    extra "You stopped choosing him."
    yujin "(The lights came back.)"
    yujin "(There was no school.)"
    yujin "(No hallway.)"
    yujin "(No classroom.)"
    yujin "(No Jeha.)"
    yujin "(No extra.)"
    yujin "(Just a blank white screen.)"
    yujin "(And one sentence.)"
    yujin "(WRITE YOUR OWN ENDING.)"

    return